name: Pylint Code Analysis

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  pylint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11", "3.12"]
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint
        pip install -r requirements.txt
    
    - name: Analysing the code with pylint
      run: |
        pylint --output-format=colorized \
               --rcfile=.pylintrc \
               --fail-under=7.0 \
               bot_init.py main.py config.py modules/
    
    - name: Generate pylint report
      run: |
        mkdir -p pylint-reports
        pylint --output-format=text \
               --rcfile=.pylintrc \
               bot_init.py main.py config.py modules/ > pylint-reports/report.txt || true
        echo "Pylint analysis completed"
    
    - name: Upload pylint report
      uses: actions/upload-artifact@v4
      with:
        name: pylint-report-${{ matrix.python-version }}
        path: pylint-reports/
        retention-days: 30
  